<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.kiwiproject</groupId>
        <artifactId>kiwi-parent</artifactId>
        <version>3.0.44</version>
    </parent>

    <artifactId>postgres-leader-latch</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>${project.groupId}:${project.artifactId}</name>
    <description>
        A framework-independent library providing leader election (a leader latch) for multiple instances of
        the same logical service, using Postgres advisory locks as the backend.
    </description>
    <url>https://github.com/kiwiproject/postgres-leader-latch</url>
    <inceptionYear>2026</inceptionYear>

    <scm>
        <connection>scm:git:https://github.com/kiwiproject/postgres-leader-latch.git</connection>
        <developerConnection>scm:git:git@github.com:kiwiproject/postgres-leader-latch.git</developerConnection>
        <url>https://github.com/kiwiproject/postgres-leader-latch</url>
        <tag>HEAD</tag>
    </scm>

    <properties>

        <!-- Versions for required dependencies -->
        <kiwi.version>5.4.0</kiwi.version>
        <kiwi-bom.version>3.3.4</kiwi-bom.version>

        <!-- Versions for test dependencies -->
        <kiwi-test.version>4.3.0</kiwi-test.version>

        <!-- Sonar properties -->
        <sonar.projectKey>kiwiproject_postgres-leader-latch</sonar.projectKey>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.kiwiproject</groupId>
                <artifactId>kiwi-bom</artifactId>
                <version>${kiwi-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.kiwiproject</groupId>
                <artifactId>kiwi</artifactId>
                <version>${kiwi.version}</version>
            </dependency>

            <dependency>
                <groupId>org.kiwiproject</groupId>
                <artifactId>kiwi-test</artifactId>
                <version>${kiwi-test.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- required dependencies -->

        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>

        <dependency>
            <groupId>org.kiwiproject</groupId>
            <artifactId>kiwi</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- test dependencies -->

        <dependency>
            <groupId>org.kiwiproject</groupId>
            <artifactId>kiwi-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-postgresql</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
